apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.serviceAccountName }}
  namespace: {{ .Values.operator.namespace }}
roleRef:
  kind: ClusterRole
  name: mysql-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io