apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: {{ .Values.operator.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: {{ .Values.operator.serviceAccountName }}
      containers:
      - name: mysql-operator
        image: {{ .Values.operator.image }}
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "mysql-operator"