apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otus
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes-networks
    repoURL: 'https://github.com/Kuber-2024-10OTUS/kadyrov2_repo.git'
    targetRevision: kubernetes-networks
    directory:
      recurse: false
  project: default
