apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otus
spec:
  destination:
    name: ''
    namespace: homeworkhelm
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes-templating/kube-app-chart
    repoURL: 'https://github.com/Kuber-2024-10OTUS/kadyrov2_repo.git'
    targetRevision: kubernetes-templating
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2