pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the application...'
                cmd.sh 
                
                // Здесь могут быть команды для сборки вашего приложения, например:
                // sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                // Здесь могут быть команды для запуска тестов, например:
                // sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
                // Здесь могут быть команды для деплоя вашего приложения, например:
                // sh 'scp target/myapp.jar user@server:/path/to/deploy'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}