pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the application...'
                sh ' chmod +x ./CI/cmd.sh'
                sh './CI/cmd.sh'   
                 
                // Здесь могут быть команды для сборки вашего приложения, например:
                // sh 'mvn clean package'
            }
        }
        
       stage('Test') {
            steps {
                sh './CI/cmd.sh test'
            }
        }
        
        stage('Deploy') {
            steps {
                sh './CI/cmd.sh deploy'
            }
        }

    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}