apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: homework
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1      
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 50
            periodSeconds: 100
        volumeMounts:
          # - name: workdir
          #   mountPath: /homework
          - name: config-nginx
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: config-text-file
            mountPath: /homework/conf
          - name: data-volume
            mountPath: /homework
      nodeSelector:
        homework: "true"
      initContainers:
      - name: install
        image: busybox:1.28
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://info.cern.ch
        volumeMounts:
        # - name: workdir
        #   mountPath: /init
        - name: data-volume
          mountPath: /init
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}
      - name: config-nginx
        configMap:
          name: nginx-config
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: config-text-file
        configMap:
          name: config-text-file
          items:
            - key: test.txt
              path: test.txt
      - name: data-volume
        persistentVolumeClaim:
         claimName: app-pvc