kubectl delete -f ./deployment.yaml
kubectl delete -f ./nginx-config.yaml
kubectl delete -f ./cm.yaml
kubectl delete -f ./pvc.yaml
kubectl delete -f ./service.yaml
kubectl delete -f ./ingress.yaml
kubectl delete -f ./controller.yaml
kubectl apply -f ./deployment.yaml
kubectl apply -f ./nginx-config.yaml
kubectl apply -f ./cm.yaml
kubectl apply -f ./pvc.yaml
kubectl apply -f ./service.yaml
kubectl apply -f ./controller.yaml
kubectl apply -f ./ingress.yaml